---
assets:
  - name: trivy
    tag: 0.57.0
    build_args:
      TRIVY_BASE_IMAGE: docker.io/aquasec/trivy
      TRIVY_BASE_TAG: 0.57.0
      TRIVY_BASE_REPO: trivy
      TRIVY_BASE_OWNER: aquasec
      TRIVY_BASE_REGISTRY: docker.io
      TRIVY_DB_IMAGE: public.ecr.aws/aquasecurity/trivy-db
      TRIVY_DB_REGISTRY: public.ecr.aws
      TRIVY_DB_OWNER: aquasecurity
      TRIVY_DB_REPO: trivy-db
      TRIVY_DB_TAG: 2
