images:
  - name: trivy
    type: image
    source: docker.io
    owner: aquasec32
    repo: trivy1
  - name: trivy-db
    type: oci
    source: public.ecr.aws
    owner: aquasecurity
    repo: trivy-db
  - name: semgrep
    type: image
    source: docker.io
    owner: returntocorp
    repo: semgrep