name: 'Legitify CIS GitHub Scan'
description: 'Run Legitify CIS compliance scan on GitHub repositories'
author: 'Kong'

inputs:
  github_token:
    description: 'GitHub token with appropriate permissions for Legitify scan'
    required: true
  repositories:
    description: 'Comma-separated list of repositories to scan (e.g., "owner/repo1,owner/repo2")'
    required: true
  # fail_on_findings:
  #   description: 'Fail job if Legitify detects CIS compliance issues'
  #   required: false
  #   default: 'false'
  upload_code_scanning:
    description: 'Upload results to GitHub Code Scanning'
    required: false
    default: 'true'
  # scorecard:
  #   description: 'Enable OpenSSF Scorecard integration'
  #   required: false
  #   default: 'no'
  artifact_name:
    description: 'Name for the artifact containing scan results'
    required: false
    default: 'legitify-cis-scan-results'


runs:
  using: 'composite'
  steps:
    - name: Set debug logging for Legitify
      shell: bash
      run: |
        if [[ "$ACTIONS_STEP_DEBUG" == "true" ]]; then
          echo "LEGITIFY_DEBUG=true" >> $GITHUB_ENV
          echo "::notice::Debug logging enabled for Legitify scan"
        else
          echo "LEGITIFY_DEBUG=false" >> $GITHUB_ENV
        fi

    - name: Run Legitify CIS Scan
      id: legitify-scan
      uses: Legit-Labs/legitify@038aa49473a6974a3ef79f6c76b949b689d23282
      continue-on-error: true
      with:
        github_token: ${{ inputs.github_token }}
        repositories: ${{ inputs.repositories }}
        upload_code_scanning: ${{ inputs.upload_code_scanning }}
    

    - name: Check if output files exist
      id: legitify-reports
      if: ${{ steps.legitify-scan.conclusion == 'success' }}
      shell: bash
      run: |
        if ls legitify-output.* 1> /dev/null 2>&1; then
          echo "files_exist=true" >> $GITHUB_OUTPUT
          echo "::notice::Legitify output files found"
          ls -la legitify-output.*
        else
          echo "files_exist=false" >> $GITHUB_OUTPUT
          echo "::warning::No Legitify output files found"
        fi

    - name: Upload outputs as Workflow Artifacts
      if: ${{ steps.legitify-scan.conclusion == 'success' && steps.legitify-reports.outputs.files_exist == 'true' }}
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.artifact_name }}
        path: legitify-output.*

    - name: Upload SARIF as Code Scanning Results
      if: ${{ inputs.upload_code_scanning == 'true' && steps.legitify-scan.conclusion == 'success' && steps.legitify-reports.outputs.files_exist == 'true' }}
      continue-on-error: true
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: legitify-output.sarif
        category: "legitify-report"

    # - name: Check scan results
    #   shell: bash
    #   run: |
    #     if [[ "${{ steps.legitify-scan.outcome }}" == "failure" ]]; then
    #       echo "::warning::Legitify CIS scan detected compliance issues"
    #       echo "SCAN_FAILED=true" >> $GITHUB_ENV
    #     else
    #       echo "::notice::Legitify CIS scan completed successfully"
    #       echo "SCAN_FAILED=false" >> $GITHUB_ENV
    #     fi

    # - name: Fail on CIS compliance issues
    #   if: ${{ always() && inputs.fail_on_findings == 'true' && env.SCAN_FAILED == 'true' }}
    #   shell: bash
    #   run: |
    #     echo "::error::Legitify CIS scan detected compliance issues and fail_on_findings is enabled"
    #     echo "::error::Check the scan results artifact: ${{ inputs.artifact_name }}"
    #     exit 1

    # - name: Upload artifact to Workflow
    #   if: always()
    #   uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
    #   with:
    #     name: ${{ inputs.artifact_name }}
    #     path: |
    #       legitify-output.json
    #       legitify-*.json
    #       legitify-*.sarif
    #       *.json
    #       *.sarif
    #     if-no-files-found: warn


    # - name: Summary
    #   if: always()
    #   shell: bash
    #   run: |
    #     echo "## Legitify CIS Scan Summary" >> $GITHUB_STEP_SUMMARY
    #     echo "**Repositories scanned:** ${{ inputs.repositories }}" >> $GITHUB_STEP_SUMMARY
    #     echo "**Scan status:** ${{ steps.legitify-scan.outcome }}" >> $GITHUB_STEP_SUMMARY
    #     echo "**Artifact name:** ${{ inputs.artifact_name }}" >> $GITHUB_STEP_SUMMARY
    #     if [[ "${{ env.SCAN_FAILED }}" == "true" ]]; then
    #       echo "**Result:** ⚠️ Compliance issues detected" >> $GITHUB_STEP_SUMMARY
    #     else
    #       echo "**Result:** ✅ No compliance issues found" >> $GITHUB_STEP_SUMMARY
    #     fi