name: Trivy Docker Scan
description: Scan a Docker image using Trivy from a private ECR repository
author: 'ABC'

inputs:
  scan_image:
    description: 'Docker image or tar file to scan'
    required: true
  compliance:
    description: 'Compliance level for the scan'
    required: false
    default: docker-cis-1.6.0
  output_file:
    description: 'Path to save the JSON report (required for JSON output)'
    required: false
  output_format:
    description: 'Specify the output format (e.g., json, table)'
    required: true
    default: json
  fail_build:
    description: 'Fail the build if vulnerability is found (only applicable for table format)'
    required: false
    default: false
    type: choice
    options:
      - 'true'
      - 'false'
  ignore_unfixed:
    description: 'Ignore unfixed vulnerabilities'
    required: false
    default: false
    type: choice
    options:
      - 'true'
      - 'false'
  trivy_db_repository:
    description: 'Custom Trivy DB repository to use for vulnerability scanning'
    required: false
    default: '992382581569.dkr.ecr.us-east-1.amazonaws.com/trivy-db:2'
  input_tar:
    description: 'Specify --input if using a tar file instead of an image reference'
    required: false
    default: ''
  skip_db_update:
    description: 'To skip DB update'
    required: true
    default: true
    type: choice
    options:
      - 'true'
      - 'false'
  skip_check_update:
    description: 'To skip IAC policies updates'
    required: true
    default: true
    type: choice
    options:
      - 'true'
      - 'false'

runs:
  using: composite
  steps:
#    - name: Set Trivy Environment Variables
#      shell: bash
#      run: |
#        export TRIVY_FORMAT=${{ inputs.output_format }}
#        export TRIVY_OUTPUT=${{ inputs.output_file }}
#        export TRIVY_IGNORE_UNFIXED=${{ inputs.ignore_unfixed }}
#        export TRIVY_COMPLIANCE=${{ inputs.compliance }}
#        export TRIVY_EXIT_CODE=${{ inputs.fail_build == 'true' && 1 || 0 }}
#        export TRIVY_DB_REPOSITORY=${{ inputs.trivy_db_repository }}
#        export TRIVY_SKIP_DB_UPDATE=${{ input.skip_db_update }}
#        export TRIVY_SKIP_CHECK_UPDATE=${{ input.skip_check_update }}

    - name: Generate docker-cis report
      uses: docker://992382581569.dkr.ecr.us-east-1.amazonaws.com/trivy:0.57.0
      with:
        entrypoint: trivy
        args:
          image ${{ inputs.input_tar != '' && '--input ' || '' }}${{ inputs.input_tar != '' && inputs.input_tar || inputs.scan_image }}
      env:
        TRIVY_FORMAT: ${{ inputs.output_format }}
        TRIVY_OUTPUT: ${{ inputs.output_file }}
        TRIVY_IGNORE_UNFIXED: ${{ inputs.ignore_unfixed }}
        TRIVY_COMPLIANCE: ${{ inputs.compliance }}
        TRIVY_EXIT_CODE: ${{ inputs.fail_build == 'true' && '1' || '0' }}
        TRIVY_DB_REPOSITORY: ${{ inputs.trivy_db_repository }}
        TRIVY_SKIP_DB_UPDATE: ${{ inputs.skip_db_update }}
        TRIVY_SKIP_CHECK_UPDATE: ${{ inputs.skip_check_update }}

