name: Trivy Docker Scan
description: Scan a Docker image using Trivy from a private ECR repository
author: 'ABC'

inputs:
  scan_image:
    description: 'Docker image or tar file to scan'
    required: true
  compliance:
    description: 'Compliance level for the scan'
    required: true
    default: docker-cis-1.6.0
  output_file:
    description: 'Path to save the JSON report'
    required: true

runs:
  using: composite
  steps:
    - name: Generate docker-cis JSON report
      uses: docker://992382581569.dkr.ecr.us-east-1.amazonaws.com/trivy:0.57.0
      with:
        entrypoint: trivy
        args: "image --input ${{ inputs.scan_image }} --compliance ${{ inputs.compliance }} -f json --ignore-unfixed -o ${{ inputs.output_file }}"
