name: Semgrep SAST
description: Semgrep SAST
author: 'Kong'


runs:
  using: composite
  steps:

    - name: SAST Scan
      # TODO: Define a tagging mechanism for dependency manager version updates 
      # Also for controlled rollouts
      uses: docker://418272760313.dkr.ecr.us-east-1.amazonaws.com/k-internal/semgrep/semgrep@sha256:74935f447159a10cf36c6521fc30f1b3a0930c8083aa11b2852fa8c2a00c2871
      with:
        entrypoint: semgrep
        args:
          ci --config auto --sarif -o semgrep_${{ github.sha }}.sarif --no-autofix ${{ inputs.additional_config }}
