name: Semgrep SAST
description: Semgrep SAST
author: 'Kong'


runs:
  using: composite
  steps:

    - name: SAST Scan
      uses: docker://992382581569.dkr.ecr.us-east-1.amazonaws.com/semgrep:1.96.0
      with:
        entrypoint: semgrep
        args:
          ci --config auto --sarif -o semgrep_${{ github.sha }}.sarif --no-autofix ${{ inputs.additional_config }}

