name: Login to Kong AWS Cloud
description: Step to authenticate to AWS and login to ECR
author: 'Kong'

runs:
  using: composite
  steps:
  - name: Configure AWS Credentials
    uses: aws-actions/configure-aws-credentials@v4
    id: creds
    with:
      aws-region: us-east-1
      role-to-assume: arn:aws:iam::418272760313:role/ecr-identity-provider-role
      role-session-name: GitHub_to_AWS_via_FederatedOIDC

  - name: Login to ECR
    uses: docker/login-action@v3
    with:
      registry: 418272760313.dkr.ecr.us-east-1.amazonaws.com
      username: ${{ steps.creds.outputs.aws-access-key-id }}
      password: ${{ steps.creds.outputs.aws-secret-access-key }}

#  - name: Login to Amazon ECR
#    uses: aws-actions/amazon-ecr-login@v2