name: Login to Kong AWS Cloud
description: Step to authenticate to AWS and login to ECR
author: 'Kong'

runs:
  using: composite
  steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      id: creds
      with:
        aws-region: ${{env.REGION}}
        role-to-assume: arn:aws:iam::${{env.AWS_ACCOUNT_ID}}:role/ecr-identity-provider-role
        role-session-name: GitHub_to_AWS_via_FederatedOIDC

#    - name: Login to ECR
#      uses: docker/login-action@v3
#      with:
#        registry: ${{ needs.metadata.outputs.ecr_registry }}
#        username: ${{ steps.creds.outputs.aws-access-key-id }}
#        password: ${{ steps.creds.outputs.aws-secret-access-key }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2
