name: Independent Releases

on:
  push:
    branches:
      - independent-releases

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install PNPM
        shell: bash
        run: |
          npm i -g pnpm
          pnpm --version

      - name: Dependency Cache
        id: dependency-cache
        uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: pnpm-20-${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Install Dependencies
        shell: bash
        run: |
          pnpm install --frozen-lockfile
          pnpm add -D conventional-changelog-metahub -w
          echo "Printing package.json"
          cat package.json
          ls 
      
      

      - name: Configure Git
        run: |
          git config --global user.name 'PankajMouriya'
          git config --global user.email 'pankaj.mouriya@konghq.com'
          git status
          echo "Printing git diff"
          git diff
          git add -A
          git commit -m "adding pnpm-lock.yml"
          

      - name: Lerna Dry Run
        run: | 
          pnpm lerna version --conventional-commits --yes
          pnpm version:ci
