name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch: {}

jobs:
  test-release:
    name: test-release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install PNPM
        shell: bash
        run: |
          npm i -g pnpm
          pnpm --version

      - name: Dependency Cache
        id: dependency-cache
        uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: pnpm-20-${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Install Dependencies
        if: ${{ steps.dependency-cache.outputs.cache-hit != 'true' }}
        shell: bash
        run: pnpm i

      - name: Release new versions
        shell: bash
        run: |
          git checkout ${{ github.head_ref }}
          git config --local user.name "${{ vars.GH_APP__KONG__BOT_USERNAME }}"
          git config --local user.email "${{ vars.GH_APP__KONG__BOT_EMAIL }}"
          pnpm version:dry-run

  # TODO when raising PR in Public shared actions
  # A Slack Webhook will be provisioned depending upon notification type
  # Update webhook URL as secret within Github PSA repo
  notify-slack:
    name: Slack Notification
    if: ${{ always() && github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    needs:
      - test-release
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v3

      # Success Notification
      # Secret Name: SLACK_WEBHOOK_URL_NOTIFY_SUCCESS
      # Slack channel "notify-public-shared-actions"
      - name: Send Success Notification
        if: ${{ needs.test-release.result == 'success' }}
        uses: edge/simple-slack-notify@v1
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL_NOTIFY_SUCCESS }}
        with:
          status: success
          success_text: '<${env.GITHUB_SERVER_URL}/${env.GITHUB_REPOSITORY}/actions/runs/${env.GITHUB_RUN_ID}|${env.GITHUB_WORKFLOW} (${env.GITHUB_RUN_NUMBER})> workflow completed successfully :github-mona:'
          fields: |
            [{ "title": "Repository", "value": "<${env.GITHUB_SERVER_URL}/${env.GITHUB_REPOSITORY}|${env.GITHUB_REPOSITORY}>", "short": true },
             { "title": "Branch", "value": "<${env.GITHUB_SERVER_URL}/${env.GITHUB_REPOSITORY}/tree/${env.GITHUB_HEAD_REF || env.GITHUB_REF.substring(11)}|${env.GITHUB_HEAD_REF || env.GITHUB_REF.substring(11)}>", "short": true },
             { "title": "Revision", "value": "<${env.GITHUB_SERVER_URL}/${env.GITHUB_REPOSITORY}/commit/${env.GITHUB_SHA}|${env.GITHUB_SHA.substring(0,7)}>", "short": true }]

      # Failure Notification
      # Secret Name: SLACK_WEBHOOK_URL_NOTIFY_FAILURE
      # Slack channel "alert-public-shared-actions"
      - name: Send Failure Notification
        if: ${{ needs.test-release.result == 'failure' }}
        uses: edge/simple-slack-notify@v1
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL_NOTIFY_FAILURE }}
        with:
          status: failure
          failure_text: '<${env.GITHUB_SERVER_URL}/${env.GITHUB_REPOSITORY}/actions/runs/${env.GITHUB_RUN_ID}|${env.GITHUB_WORKFLOW} (${env.GITHUB_RUN_NUMBER})> workflow failed :github-mona:'
          fields: |
            [{ "title": "Repository", "value": "<${env.GITHUB_SERVER_URL}/${env.GITHUB_REPOSITORY}|${env.GITHUB_REPOSITORY}>", "short": true },
             { "title": "Branch", "value": "<${env.GITHUB_SERVER_URL}/${env.GITHUB_REPOSITORY}/tree/${env.GITHUB_HEAD_REF || env.GITHUB_REF.substring(11)}|${env.GITHUB_HEAD_REF || env.GITHUB_REF.substring(11)}>", "short": true },
             { "title": "Revision", "value": "<${env.GITHUB_SERVER_URL}/${env.GITHUB_REPOSITORY}/commit/${env.GITHUB_SHA}|${env.GITHUB_SHA.substring(0,7)}>", "short": true }]
