name: Independent Releases

on:
  push:
    branches:
      - independent-releases

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install PNPM
        shell: bash
        run: |
          npm i -g pnpm
          pnpm --version

      - name: Install Dependencies
        shell: bash
        run: pnpm i

      - name: Configure Git
        run: |
          git config --global user.name 'PankajMouriya'
          git config --global user.email 'pankaj.mouriya@konghq.com'
