name: CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: read

jobs:
  setup-and-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 9
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install Dependencies
        run: |
          pnpm install --frozen-lockfile

      - name: Commit lint
        uses: wagoid/commitlint-github-action@v5
        with:
          failOnWarnings: true
      
      - name: Run ESLint
        run: pnpm lint

  slack_notification:
    name: Slack Notification
    runs-on: ubuntu-latest
    needs: setup-and-lint
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Success Notification
      - name: Send Success Slack Notification
        if: ${{ needs.setup-and-lint.result == 'success' }}
        uses: slackapi/slack-github-action@v2.0.0
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK_URL_NOTIFY_PUBLIC_SHARED_ACTIONS }}
          webhook-type: incoming-webhook
          payload: |
            blocks:
              - type: "header"
                text:
                  type: "plain_text"
                  emoji: true
                  text: "Workflow Success"
              - type: "section"
                text:
                  type: "mrkdwn"
                  text: ":white_check_mark: ${{ github.workflow }} workflow *successfully* ran within ${{ github.repository }}"
              - type: "section"
                fields:
                  - type: "mrkdwn"
                    text: "*Repository:*\n<${{ github.server_url }}/${{ github.repository }}|${{ github.repository }}>"
                  - type: "mrkdwn"
                    text: "*Branch:*\n<${{ github.server_url }}/${{ github.repository }}/tree/${{ github.head_ref || steps.slack-variables.outputs.fallback-branch-name }}|${{ github.head_ref || steps.slack-variables.outputs.fallback-branch-name }}>"
                  - type: "mrkdwn"
                    text: "*Workflow Run:*\n<${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|${{ github.run_number }}>"
                  - type: "mrkdwn"
                    text: "*Commit:*\n<${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}|${{ steps.slack-variables.outputs.short-commit-hash }}>"

      # Failure Notification
      - name: Send Failure Slack alert
        if: ${{ needs.setup-and-lint.result == 'failure' }}
        uses: slackapi/slack-github-action@v2.0.0
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK_URL_ALERT }}
          webhook-type: incoming-webhook
          payload: |
            text: ":x: This is a *failure* notification from ${{ github.repository }} for workflow ${{ github.workflow }}"
            blocks:
              - type: "header"
                text:
                  type: "plain_text"
                  emoji: true
                  text: "Workflow Failure"
              - type: "section"
                text:
                  type: "mrkdwn"
                  text: ":x: This is a *failure* notification from ${{ github.repository }} for workflow ${{ github.workflow }}"