name: SCA Directory Scan

on:
  pull_request:
    branches:
    - main
  push:
    branches:
    - main
    tags:
    - '*'
  workflow_dispatch: {}

jobs:
  test-sca-dir:
    env:
      TEST_REPOSITORY: "pankajmouriyakong/ai-security-analyzer"
    runs-on: ubuntu-latest
    permissions:
      contents: write # publish sbom to GH releases/tag assets
      issues: read
      checks: write
      pull-requests: write
      security-events: write
    name: Test Repository Scan
    steps:
        - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
        - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
          with:
            repository: ${{env.TEST_REPOSITORY}}
            path: ${{env.TEST_REPOSITORY}}
            token: ${{ secrets.GH_READ_PAT }}
        - name: Scan Directory
          id: scan-dir
          uses: ./security-actions/sca
          with:
            asset_prefix: test.ai-security-analyzer
            dir: ${{env.TEST_REPOSITORY}}
            upload-sbom-release-assets: true
            fail_build: false
            codeql_upload: true
