name: SCA Directory Scan

on:
  pull_request:
    branches:
    - main
  push:
    branches:
    - main
    tags:
    - '*'
  workflow_dispatch: {}

jobs:
  test-sca-dir:
    env:
      TEST_REPOSITORY: "${{github.repository_owner}}/insomnia"
    runs-on: ubuntu-latest
    permissions:
      contents: write # publish sbom to GH releases/tag assets
      issues: read
      checks: write
      pull-requests: write
    name: Test Repository Scan
    steps:
        - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
          with:
            repository: ${{env.TEST_REPOSITORY}}
            path: ${{env.TEST_REPOSITORY}}
        - name: Scan Directory
          id: scan-dir
          uses: ./security-actions/sca
          with:
            asset_prefix: test.insomnia
            dir: ${{env.TEST_REPOSITORY}}
            upload-sbom-release-assets: true
            fail_build: false
  
  slack_notification:
    name: Slack Notification
    runs-on: ubuntu-latest
    needs: test-sca-dir
    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      # Success Notification
      - name: Send Success Slack Notification
        if: ${{ needs.test-sca-dir.result == 'success' }}
        uses: ./slack-actions/workflow-notification
        with:
          slack-webhook-url: ${{ secrets.SLACK_WEBHOOK_URL_NOTIFY_PUBLIC_SHARED_ACTIONS }}
          status: success
          payload: |
            {
              "text": "Completely custom Slack message for CI",
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "emoji": true,
                    "text": "CI Workflow Success"
                  }
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*Repository:*\n<${{ github.server_url }}/${{ github.repository }}|${{ github.repository }}>"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Branch:*\n<${{ github.server_url }}/${{ github.repository }}/tree/${{ github.ref_name }}|${{ github.ref_name }}>"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Workflow Run:*\n<${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|${{ github.run_number }}>"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*TriggeredByCommit:*\n<${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}|${{ github.sha }}>"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Triggered By:*\n${{ github.actor }}"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Commit Author:*\n${{ github.event.head_commit.author.name }}"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Event Name:*\n${{ github.event_name }}"
                    }
                  ]
                }
              ]
            }
    
      # Failure Notification
      - name: Send Failure Slack alert
        if: ${{ needs.test-sca-dir.result == 'failure' }}
        uses: ./slack-actions/workflow-notification
        with:
          slack-webhook-url: ${{ secrets.SLACK_WEBHOOK_URL_ALERT_PUBLIC_SHARED_ACTIONS }}
          status: failure
          payload: |
            {
              "text": "Completely custom Slack message for CI",
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "emoji": true,
                    "text": "CI Workflow Failure"
                  }
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*Repository:*\n<${{ github.server_url }}/${{ github.repository }}|${{ github.repository }}>"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Branch:*\n<${{ github.server_url }}/${{ github.repository }}/tree/${{ github.ref_name }}|${{ github.ref_name }}>"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Workflow Run:*\n<${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|${{ github.run_number }}>"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*TriggeredByCommit:*\n<${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}|${{ steps.slack-variables.outputs.short-commit-hash }}>"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Triggered By:*\n${{ github.actor }}"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Commit Author:*\n${{ github.event.head_commit.author.name }}"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Event Name:*\n${{ github.event_name }}"
                    }
                  ]
                }
              ]
            }
        