name: Multi-Registry Image Sync

on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches:
      - 'ecr-private'
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  sync_images:
    runs-on: ubuntu-latest
    env:
      DOCKERHUB_USERNAME: ${{ secrets.GHA_DOCKERHUB_PULL_USER }}
      DOCKERHUB_PASSWORD: ${{ secrets.GHA_KONG_ORG_DOCKERHUB_PUBLIC_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

#      - name: Configure AWS credentials
#        uses: aws-actions/configure-aws-credentials@v4
#        with:
#          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#          aws-region: us-east-1

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::992382581569:role/ecr-private-role
          role-session-name: GitHub_to_AWS_via_FederatedOIDC

      - name: Sts GetCallerIdentity
        run: |
            aws sts get-caller-identity

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y python3-pip
          pip3 install yq
          chmod +x .github/scripts/sync_images.sh

      - name: Install regsync
        run: |
          curl -Lo /usr/local/bin/regsync https://github.com/regclient/regclient/releases/download/v0.4.5/regsync-linux-amd64
          chmod +x /usr/local/bin/regsync
          echo "regsync installed"
          regsync -h

      - name: Execute the image sync script
        run: |
          ./.github/scripts/sync_images.sh
        env:
          DOCKERHUB_USERNAME: ${{ secrets.GHA_DOCKERHUB_PULL_USER }}
          DOCKERHUB_PASSWORD: ${{ secrets.GHA_KONG_ORG_DOCKERHUB_PUBLIC_TOKEN }}
