name: CIS GH Legitify Compliance Scan

on:
  pull_request: {}
  push:
    branches: 
    - master
    - main
  workflow_dispatch: {}


permissions:
  contents: read
  discussions: read
  issues: read
  pull-requests: read
  security-events: write

jobs:
  cis-compliance-scan:
    name: CIS Compliance Scan
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Run Legitify CIS Scan
        uses: ./security-actions/scan-gh-cis
        with:
          github_token: ${{ secrets.LEGITIFY_TOKEN }}
          upload_code_scanning: 'true'  
          repositories: "pankajmouriyakong/httpsnippet"

  slack_notification:
    name: Slack Notification
    runs-on: ubuntu-latest
    # if: ${{ always() && github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    if: ${{ always() }}
    needs: [cis-compliance-scan]
    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      # Success Notification
      - name: Send Success Slack Notification
        if: ${{ needs.cis-compliance-scan.result == 'success' }}
        uses: ./slack-actions/workflow-notification
        with:
          slack-webhook-url: ${{ secrets.SLACK_WEBHOOK_URL_NOTIFY_PUBLIC_SHARED_ACTIONS }}
          status: success
          payload: |
            {
              "text": "✅ CIS Scan Workflow Success - ${{ github.repository }}",
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "emoji": true,
                    "text": "✅ CIS Scan Workflow ran Successfully"
                  }
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*Repository:*\n<${{ github.server_url }}/${{ github.repository }}|${{ github.repository }}>"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Branch:*\n<${{ github.server_url }}/${{ github.repository }}/tree/${{ github.ref_name }}|${{ github.ref_name }}>"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Workflow Run:*\n<${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|Run #${{ github.run_number }}>"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Triggered By:*\n${{ github.actor }}"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Commit:*\n<${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}|${{ github.event.head_commit.message }}>"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Author:*\n${{ github.event.head_commit.author.name }}"
                    }
                  ]
                },
                {
                  "type": "context",
                  "elements": [
                    {
                      "type": "mrkdwn",
                      "text": "🕐 Completed at: ${{ github.event.head_commit.timestamp }} | Event: `${{ github.event_name }}` | Run ID: ${{ github.run_id }}"
                    }
                  ]
                }
              ]
            }
    
      # Failure Notification
      - name: Send Failure Slack Alert
        if: ${{ needs.cis-compliance-scan.result == 'failure' }}
        uses: ./slack-actions/workflow-notification
        with:
          slack-webhook-url: ${{ secrets.SLACK_WEBHOOK_URL_ALERT_PUBLIC_SHARED_ACTIONS }}
          status: failure
          payload: |
            {
              "text": "🚨 CIS Scan Workflow FAILED - ${{ github.repository }} - Immediate attention required!",
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "emoji": true,
                    "text": "🚨 CIS Scan Workflow has FAILED"
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "⚠️ *Action Required:* The CIS Scan generation has failed and needs immediate attention"
                  }
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*Repository:*\n<${{ github.server_url }}/${{ github.repository }}|${{ github.repository }}>"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Branch:*\n<${{ github.server_url }}/${{ github.repository }}/tree/${{ github.ref_name }}|${{ github.ref_name }}>"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Failed Run:*\n<${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|🔍 View Logs - Run #${{ github.run_number }}>"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Triggered By:*\n${{ github.actor }}"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Commit:*\n<${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}|${{ github.event.head_commit.message }}>"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Author:*\n${{ github.event.head_commit.author.name }}"
                    }
                  ]
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*🔧 Quick Actions:*\n• <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|View detailed logs>\n• <${{ github.server_url }}/${{ github.repository }}/actions|Check recent workflow history>\n"
                  }
                },
                {
                  "type": "context",
                  "elements": [
                    {
                      "type": "mrkdwn",
                      "text": "🕐 Failed at: ${{ github.event.head_commit.timestamp }} | Event: `${{ github.event_name }}` | Investigation Needed"
                    }
                  ]
                }
              ]
            }    