name: Mirroring

on:
  pull_request:
    branches:
    - main
  push:
    branches:
    - main
    tags:
    - '*'
  workflow_dispatch: {}

permissions:
  contents: read
  discussions: read
  issues: read
  pull-requests: read
  id-token: write

env:
  AWS_ACCOUND_ID: 992382581569
  #KONG_ECR_URI: ${{ secrets.AWS_ACCOUND_ID }}.dkr.ecr.us-east-1.amazonaws.com
  REGION: us-east-1

jobs:
  metadata:
    name: Metadata
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.config.outputs.matrix }}
    steps:
    - uses: actions/checkout@v3
    - name: Construct tooling matrix
      id: config
      run: |
        matrix_file=".github/dependencies.yml"
        echo "matrix=$(yq -I=0 -o=json $matrix_file)" >> $GITHUB_OUTPUT

        ASSETS=$(yq -I=0 -o=json '.assets' .github/dependencies.yml | jq -c '.[]')
        echo "Assets: $ASSETS"
        echo "assets=$(echo $ASSETS | jq -c -s '. | map({name: .name, build_args: .build-args})')" >> $GITHUB_OUTPUT

        # assets=$(yq -I=0 -o=json '.assets' .github/dependencies.yml | jq -c '.[]')
        # echo "Assets: $assets"
        # echo "assets=$(echo $assets | jq -c -s '. | map({name: .name, build_args: .build-args})')" >> $GITHUB_OUTPUT
  
  # TODO: Enhance this job to run per asset frequency schedule
  build-publish-assets:
    runs-on: ubuntu-latest
    needs: metadata
    name: Build Asset - ${{ matrix.name }}
    strategy:
      fail-fast: false
      matrix:
        #include: "${{ fromJSON(needs.metadata.outputs.matrix)['assets'] }}"
        assets: ${{fromJson(needs.metadata.outputs.assets)}}
        
    if: ${{ github.event_name == 'schedule' || github.event_name == 'workflow_dispatch' }}
    steps:
    - uses: actions/checkout@v4

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: us-east-1
        role-to-assume: arn:aws:iam::992382581569:role/ecr-private-role-to-pull
        role-session-name: GitHub_to_AWS_via_FederatedOIDC

    - name: Sts GetCallerIdentity
      shell: bash
      run: |
        aws sts get-caller-identity

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.KONG_ECR_REGISTRY }}
        sep-tags: ","
        tags: |
          type=raw,${{ matrix.asset.tag }}
      env:
        KONG_ECR_REGISTRY: 992382581569.dkr.ecr.${{ env.REGION }}.amazonaws.com
    
    # - name: Set Docker build args
    #   id: docker_build_args
    #   run: |
    #     platforms="${{ matrix.docker-platforms }}"
    #     if [[ -z "$platforms" ]]; then
    #       platforms="linux/amd64"
    #     fi
    #     echo "platforms=$platforms" >> $GITHUB_OUTPUT

    - name: Build Docker Image
      uses: docker/build-push-action@v5
      id: image
      with:
        file: security-actions/dockerfiles/${{ matrix.asset.name }}.Dockerfile
        context: .
        push: true
        pull: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        # platforms: ${{ steps.docker_build_args.outputs.platforms }}
        # build-args: |
        #   ${{fromJson(matrix.build-args)}}
        build-args: ${{ toJson(matrix.asset.build_args) }}

        # these 2 options are needed so that the MediaType of the manifest is
        # OCI-compliant for other downstream integrations
        # see also:
        #   - https://github.com/docker/buildx/issues/1507
        #   - https://github.com/docker/buildx/issues/1509#issuecomment-1378538197
        provenance: false
        outputs: type=image,oci-mediatypes=true

