name: Releases
on:
  push:
    branches:
      - main
      - independent-releases

jobs:
  release:
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/independent-releases' }}
    name: Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Release Action
        uses: ./release-action
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}
          node_version: '20'
          bot_username: ${{ vars.GH_APP__KONG__BOT_USERNAME }}
          bot_email: ${{ vars.GH_APP__KONG__BOT_EMAIL }}
