name: Publish Release

on:
  # workflow_run:
  #   workflows: ["ci"]
  #   types:
  #     - completed
  #   branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.SECURITY_BOT_PSA_PAT }}

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 9
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      
      # This is needed since we only cache ~/.pnpm_store instead of entire node_modules    
      - name: Install dependencies
        run: pnpm install

      - name: Setup Git Config
        shell: bash
        run: |
          git checkout ${{ github.head_ref }}
          git config --local user.name "kong-security-bot"
          git config --local user.email "117922193+kong-security-bot@users.noreply.github.com"

      # This step will create a tag and also release
      - name: Provision tags and make a release
        env:
          GH_TOKEN: ${{ secrets.SECURITY_BOT_PSA_PAT }}
        shell: bash
        run: |
          pnpm version:ci
          RELEASE_COMMIT="$(git rev-parse HEAD)"
          echo "release_commit=$RELEASE_COMMIT" >> "$GITHUB_OUTPUT"
      # - name: Dry-run for tagging and releases
      #   shell: bash
      #   run: pnpm version:dry-run

  slack_notification:
    name: Slack Notification
    runs-on: ubuntu-latest
    needs: release
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Success Notification
      - name: Send Success Slack Notification
        if: ${{ needs.setup-and-lint.result == 'success' }}
        uses: slackapi/slack-github-action@v2.0.0
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK_URL_NOTIFY_PUBLIC_SHARED_ACTIONS }}
          webhook-type: incoming-webhook
          payload: |
            blocks:
              - type: "header"
                text:
                  type: "plain_text"
                  emoji: true
                  text: "Release Workflow Success"
              - type: "section"
                text:
                  type: "mrkdwn"
                  text: ":white_check_mark: ${{ github.workflow }} workflow *successfully* ran within ${{ github.repository }}"
              - type: "section"
                fields:
                  - type: "mrkdwn"
                    text: "*Repository:*\n<${{ github.server_url }}/${{ github.repository }}|${{ github.repository }}>"
                  - type: "mrkdwn"
                    text: "*Branch:*\n<${{ github.server_url }}/${{ github.repository }}/tree/${{ github.head_ref || steps.slack-variables.outputs.fallback-branch-name }}|${{ github.head_ref || steps.slack-variables.outputs.fallback-branch-name }}>"
                  - type: "mrkdwn"
                    text: "*Workflow Run:*\n<${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|${{ github.run_number }}>"
                  - type: "mrkdwn"
                    text: "*TriggerByCommit:*\n<${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}|${{ steps.slack-variables.outputs.short-commit-hash }}>"
                  - type: "mrkdwn"
                    text: "*ReleaseCommit:*\n${{ needs.release.outputs.release_commit }}>

      # Failure Notification
      - name: Send Failure Slack alert
        if: ${{ needs.setup-and-lint.result == 'failure' }}
        uses: slackapi/slack-github-action@v2.0.0
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK_URL_ALERT }}
          webhook-type: incoming-webhook
          payload: |
            text: ":x: This is a *failure* notification from ${{ github.repository }} for workflow ${{ github.workflow }}"
            blocks:
              - type: "header"
                text:
                  type: "plain_text"
                  emoji: true
                  text: "Workflow Failure"
              - type: "section"
                text:
                  type: "mrkdwn"
                  text: ":x: This is a *failure* notification from ${{ github.repository }} for workflow ${{ github.workflow }}"