name: Release Notifications
on:
  release:
    types: [published]

jobs:

  notify-slack:
    name: Slack Notification
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Send notification
        uses: Kong/public-shared-actions/slack-actions/workflow-notification@v2
        with:
          slack-webhook-url: ${{ secrets.SLACK_WEBHOOK_URL_NOTIFY_PUBLIC_SHARED_ACTIONS }}
          status: ${{ job.status }}
          success-message: 'Successfully released <${env.GITHUB_SERVER_URL}/${env.GITHUB_REPOSITORY}/releases/tag/${{github.event.release.name}}|${{github.event.release.name}}> :octocat:'
          failure-message: 'Failed to release <${env.GITHUB_SERVER_URL}/${env.GITHUB_REPOSITORY}/releases/tag/${{github.event.release.name}}|${{github.event.release.name}}> :github-dead:'