name: Release Notifications
on:
  release:
    types: [published]

jobs:

  notify-slack:
    name: Slack Notification
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Send notification
        uses: ./slack-actions/workflow-notification
        with:
          slack-webhook-url: ${{ secrets.SLACK_WEBHOOK_URL_NOTIFY_PUBLIC_SHARED_ACTIONS }}
          status: ${{ job.status }}
          success-message: 'Successfully released <${{ env.GITHUB_SERVER_URL }}/${{ env.GITHUB_REPOSITORY }}/releases/tag/${{ github.event.release.tag_name }}|${{ github.event.release.tag_name }}> :octocat:'
          failure-message: 'Failed to release <${{ env.GITHUB_SERVER_URL }}/${{ env.GITHUB_REPOSITORY }}/releases/tag/${{ github.event.release.tag_name }}|${{ github.event.release.tag_name }}> :github-dead:'