name: Release

on:
  workflow_run:
    workflows: ["ci"]
    types:
      - completed
    branches: [ main ]
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  check_for_package_changes:
    name: check for package changes
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    outputs:
      has_package_changed: ${{ steps.lerna-check.outputs.has_package_changed }}
    steps:

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Check new releases
        shell: bash
        id: lerna-check
        run: |
          changed=$(lerna changed || true)

          echo "Changed packages:"
          echo "$changed"

          if [ -z "$changed" ]; then
            echo "No changed packages since last release."
            echo "has_package_changed=false" >> "$GITHUB_OUTPUT"
          else
            echo "Detected changed packages!"
            echo "has_package_changed=true" >> "$GITHUB_OUTPUT"
          fi


  publish:
    name: publish
    needs: check_for_package_changes
    if: ${{ needs.check_for_package_changes.outputs.has_package_changed == 'true' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      lerna_published_tags: ${{ steps.list-published-package-tags.outputs.lerna_published_tags }}
    steps:

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.SECURITY_BOT_PSA_PAT }}

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 9
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      
      # This is needed since we only cache ~/.pnpm_store instead of entire node_modules    
      - name: Install dependencies
        run: pnpm install

      - name: Setup Git Config
        shell: bash
        run: |
          git config --local user.name "kong-security-bot"
          git config --local user.email "117922193+kong-security-bot@users.noreply.github.com"

      # This step will create a tag and also release
      - name: Provision tags and make a release
        if: ${{ github.ref == 'refs/heads/main' }}
        env:
          GH_TOKEN: ${{ secrets.SECURITY_BOT_PSA_PAT }}
        shell: bash
        run: |
          pnpm version:ci
      
      # This step will list packages with their most recent tags
      - name: List packages with their latest tags & SHA Digest
        id: list-published-package-tags
        if: ${{ github.ref == 'refs/heads/main' }}
        shell: bash
        run: |
          raw_result=$(lerna list -l)
          bullet_points=""

          # Loop to fetch Tags SHA digest
          while IFS= read -r line; do
            pkg=$(echo "$line" | awk '{print $1}')
            ver=$(echo "$line" | awk '{ sub(/^v/, "", $2); print $2 }')
            tag="$pkg@$ver"
            sha=$(git rev-parse "$tag" 2>/dev/null || echo "N/A")

            # Append a bullet line: "* @pkg -> 5.0.0 -> 123abcd...."
            bullet_points+="* $pkg -> $ver -> $sha\n\n"
          done <<< "$raw_result"

          # Escape newlines so Slack sees them correctly
          result=$(echo "$bullet_points" | sed ':a;N;$!ba;s/\n/\\n/g')

          # Prepare lerna tag list as a multiline output for Slack job
          echo "lerna_published_tags<<EOF" >> $GITHUB_OUTPUT
          echo "$result" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
          
          # Publish tags result as GitHub Summary
          echo "### Published Packages" >> "$GITHUB_STEP_SUMMARY"
          echo "$raw_result"           >> "$GITHUB_STEP_SUMMARY"
      
      - name: Dry-run for tagging and releases
        if: ${{ github.ref != 'refs/heads/main' }}
        shell: bash
        run: pnpm version:dry-run

  slack_notification:
    name: Slack Notification
    runs-on: ubuntu-latest
    needs: publish
    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Success Notification
      - name: Send Success Notification
        if: ${{ needs.publish.result == 'success' }}
        uses: ./slack-actions/workflow-notification
        with:
          slack-webhook-url: ${{ secrets.SLACK_WEBHOOK_URL_NOTIFY_PUBLIC_SHARED_ACTIONS }}
          status: success
          payload: |
            {
              "text": "Completely custom Slack message for release",
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "emoji": true,
                    "text": "Release Workflow Success"
                  }
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*Repository:*\n<${{ github.server_url }}/${{ github.repository }}|${{ github.repository }}>"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Branch:*\n<${{ github.server_url }}/${{ github.repository }}/tree/${{ github.ref_name }}|${{ github.ref_name }}>"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Workflow Run:*\n<${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|${{ github.run_number }}>"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*TriggeredByCommit:*\n<${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}|${{ github.sha }}>"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Triggered By:*\n${{ github.actor }}"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Event Name:*\n${{ github.event_name }}"
                    }
                  ]
                }
              ]
            }
      
      # Publish released packages to Engineering Slack Channel
      - name: Publish packages list in Slack
        if: ${{ needs.publish.result == 'success' }}
        uses: ./slack-actions/workflow-notification
        with:
          slack-webhook-url: ${{ secrets.SLACK_WEBHOOK_URL_NOTIFY_PUBLIC_SHARED_ACTIONS }}
          status: success
          payload: |
            {
              "text": "Completely custom Slack message for release",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": ":rocket::rocket::rocket:**The following packages have been published successfully as part of the new release of Public Shared actions repository:**\n\n${{ needs.publish.outputs.lerna_published_tags }}"
                  }
                }
              ]
            }


      # Failure Notification
      - name: Send Failure Notification
        if: ${{ needs.publish.result == 'failure' }}
        uses: ./slack-actions/workflow-notification
        with:
          slack-webhook-url: ${{ secrets.SLACK_WEBHOOK_URL_ALERT_PUBLIC_SHARED_ACTIONS }}
          status: failure
          payload: |
            {
              "text": "Completely custom Slack message for release",
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "emoji": true,
                    "text": "Release Workflow Failure"
                  }
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*Repository:*\n<${{ github.server_url }}/${{ github.repository }}|${{ github.repository }}>"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Branch:*\n<${{ github.server_url }}/${{ github.repository }}/tree/${{ github.ref_name }}|${{ github.ref_name }}>"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Workflow Run:*\n<${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|${{ github.run_number }}>"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*TriggeredByCommit:*\n<${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}|${{ github.sha }}>"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Triggered By:*\n${{ github.actor }}"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Event Name:*\n${{ github.event_name }}"
                    }
                  ]
                }
              ]
            }