name: Release

on:
  workflow_run:
    workflows: ["ci"]
    types:
      - completed
    branches: [ main ]
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  publish:
    name: publish
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      published_packages: ${{ steps.list-published-packages.outputs.published_packages }}
    steps:

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.SECURITY_BOT_PSA_PAT }}

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 9
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      
      # This is needed since we only cache ~/.pnpm_store instead of entire node_modules    
      - name: Install dependencies
        run: pnpm install

      - name: Setup Git Config
        shell: bash
        run: |
          git config --local user.name "kong-security-bot"
          git config --local user.email "117922193+kong-security-bot@users.noreply.github.com"

      # This step will create a tag and also release
      - name: Provision tags and make a release
        if: ${{ github.ref == 'refs/heads/main' }}
        env:
          GH_TOKEN: ${{ secrets.SECURITY_BOT_PSA_PAT }}
        shell: bash
        run: |
          pnpm version:ci
      
      # This step will list packages with their most recent tags
      # | awk '{printf "- *%s* `%s`\n", $1, $2}')
      - name: List packages with tags
        id: list-published-packages
        if: ${{ github.ref == 'refs/heads/main' }}
        shell: bash
        run: |
          raw_result=$(lerna list -l)
          bullet_points=$(echo "$raw_result" | sed -E 's/^([^[:space:]]+)[[:space:]]+([^[:space:]]+).*/- \1 -> \2/')
          escaped_result=$(echo "$bullet_points" | sed ':a;N;$!ba;s/\n/\\n/g')
          echo "published_packages<<EOF" >> $GITHUB_OUTPUT
          echo "$escaped_result" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
          echo "### Published Packages" >> "$GITHUB_STEP_SUMMARY"
          echo "$raw_result"           >> "$GITHUB_STEP_SUMMARY"
      
      - name: Dry-run for tagging and releases
        if: ${{ github.ref != 'refs/heads/main' }}
        shell: bash
        run: pnpm version:dry-run

  slack_notification:
    name: Slack Notification
    runs-on: ubuntu-latest
    needs: publish
    if: always() && github.ref == 'refs/heads/main'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Success Notification
      - name: Send Success Notification
        if: ${{ needs.publish.result == 'success' }}
        uses: ./slack-actions/workflow-notification
        with:
          slack-webhook-url: ${{ secrets.SLACK_WEBHOOK_URL_NOTIFY_PUBLIC_SHARED_ACTIONS }}
          status: success
          payload: |
            {
              "text": "Completely custom Slack message for release",
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "emoji": true,
                    "text": "Release Workflow Success"
                  }
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*Repository:*\n<${{ github.server_url }}/${{ github.repository }}|${{ github.repository }}>"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Branch:*\n<${{ github.server_url }}/${{ github.repository }}/tree/${{ github.ref_name }}|${{ github.ref_name }}>"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Workflow Run:*\n<${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|${{ github.run_number }}>"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*TriggeredByCommit:*\n<${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}|${{ github.sha }}>"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Triggered By:*\n${{ github.actor }}"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Event Name:*\n${{ github.event_name }}"
                    }
                  ]
                }
              ]
            }
      
      # Publish released packages to Engineering Slack Channel
      - name: Publish packages list in Slack
        if: ${{ needs.publish.result == 'success' }}
        uses: ./slack-actions/workflow-notification
        with:
          slack-webhook-url: ${{ secrets.SLACK_WEBHOOK_URL_NOTIFY_PUBLIC_SHARED_ACTIONS }}
          status: success
          payload: |
            {
              "text": "Completely custom Slack message for release",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "The following packages have been published successfully:\n\n${{ needs.publish.outputs.published_packages }}"
                  }
                }
              ]
            }


      # Failure Notification
      - name: Send Failure Notification
        if: ${{ needs.publish.result == 'failure' }}
        uses: ./slack-actions/workflow-notification
        with:
          slack-webhook-url: ${{ secrets.SLACK_WEBHOOK_URL_ALERT_PUBLIC_SHARED_ACTIONS }}
          status: failure
          payload: |
            {
              "text": "Completely custom Slack message for release",
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "emoji": true,
                    "text": "Release Workflow Failure"
                  }
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*Repository:*\n<${{ github.server_url }}/${{ github.repository }}|${{ github.repository }}>"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Branch:*\n<${{ github.server_url }}/${{ github.repository }}/tree/${{ github.ref_name }}|${{ github.ref_name }}>"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Workflow Run:*\n<${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|${{ github.run_number }}>"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*TriggeredByCommit:*\n<${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}|${{ github.sha }}>"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Triggered By:*\n${{ github.actor }}"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Event Name:*\n${{ github.event_name }}"
                    }
                  ]
                }
              ]
            }