name: Secret Scan

on:
  pull_request: {}
  push:
    branches: 
    - master
    - main
  workflow_dispatch: {}


jobs:
  secret-scan:
    name: SAST
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
        with: 
          fetch-depth: 0
      - uses: ./security-actions/secret-scan
        name: secret Scanning
        with:
          fail_on_findings: 'true'
        env:
          ACTIONS_STEP_DEBUG: true

            
