name: Mirroring Process for Trivy Vuln DB

on:
  workflow_dispatch:
  push:
    branches:
      - 'decouple-trivy-image-config'
  schedule:
    - cron:  '0 */6 * * *'  # Runs every 6 hrs


env:
  AWS_ACCOUNT_ID: 418272760313
  REGION: us-east-1

permissions:
  id-token: write

jobs:
  metadata:
    name: Metadata
    runs-on: ubuntu-latest

    outputs:
      assets: ${{ steps.config.outputs.assets }}
      ecr_registry: ${{ steps.config.outputs.ecr_registry }}
    steps:
      - uses: actions/checkout@v3
      - name: Construct tooling matrix
        if: ${{ github.event_name == 'schedule' || github.event_name == 'workflow_dispatch' }}
        id: config
        run: |
          matrix_file=".github/build/docker/security-image-matrix.yml"
          assets=$(yq eval -o=json '.assets' $matrix_file)
          # Construct the dependency matrix
          # Format tooling build_args as key=value pair space separated string
          single_line_assets=$(echo "$assets" | jq -rc 'map({
            name: .name,
            build_args: (
              if (.build_args // null) == null then
                ""
              else
                .build_args |
                to_entries |
                map("\(.key)=\(.value)") |
                join(" ")
              end
            )
          })')  
          echo "ASSETS_JSON=$single_line_assets"
          echo "ecr_registry=${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.REGION }}.amazonaws.com" >> $GITHUB_OUTPUT
          echo "assets=$single_line_assets" >> $GITHUB_OUTPUT

  trivy-db-mirror:
    runs-on: ubuntu-latest
    needs: metadata
    steps:
    - uses: actions/checkout@v4

    - name: Configure AWS Credentials
      uses: ./login-aws-cloud

    - name: Oras Setup
      uses: oras-project/setup-oras@v1

    - name: Pull and Cache Trivy Vuln DB
      run: |
        DB_IMAGE=${{ matrix.asset.build_args.DB_IMAGE }}
        echo $DB_IMAGE
        trimmed_string=$(echo "$DB_IMAGE" | sed 's|^public\.ecr\.aws/||')
        echo $trimmed_string
        oras pull ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.REGION }}.amazonaws.com/trivy-db/$trimmed_string
    
        
