name: Mirroring Process for Trivy Vuln DB

on:
  workflow_dispatch:
  push:
    branches:
      - 'decouple-trivy-image-config'
  schedule:
    - cron:  '0 */6 * * *'  # Runs every 6 hrs


env:
  AWS_ACCOUNT_ID: 418272760313
  REGION: us-east-1

permissions:
  id-token: write

jobs:
  trivy-db-mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: ./login-aws-cloud

      - name: Oras Setup
        uses: oras-project/setup-oras@v1

      - name: Pull and Cache Trivy Vuln DB
        run: |
          oras pull ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.REGION }}.amazonaws.com/trivy-db/aquasecurity/trivy-db:2